import { Colors } from "../globals/colors.slint";

export component IconButton {
    in property <image> icon;
    callback on-click();

    TouchArea {
        mouse-cursor: pointer;
        Rectangle {
            border-radius: 6px;
            background: parent.pressed ? Colors.button-background-pressed : (parent.has-hover ? Colors.button-background-hovered : Colors.button-background);
            VerticalLayout {
                padding: 8px;
                Image {
                    source: icon;
                    width: 24px;
                    height: 24px;
                }
            }
        }

        clicked => {
            on-click()
        }
    }
}
