import { ScrollView } from "std-widgets.slint";
import { Colors } from "../globals/colors.slint";

export component Panel {
    Rectangle {
        background: Colors.panel-background;
        border-radius: 12px;
        ScrollView {
            height: 100%;
            width: 300px;
            VerticalLayout {
                alignment: start;
                spacing: 10px;
                padding: 8px;

                @children
            }
        }
    }
}
