import { Colors } from "../globals/colors.slint";
import { InterfaceState } from "../globals/state.slint";

export component Textfield {
    in property <string> label;
    in-out property <string> value;
    in property <string> entity-id;
    in property <string> component-name;

    // Trigger callback when value changes
    changed value => {
        if (entity-id != "" && component-name != "" && label != "") {
            InterfaceState.attribute-changed(entity-id, component-name, label, value);
        }
    }

    VerticalLayout {
        padding: 12px;
        spacing: 4px;
        height: self.preferred-height;

        Text {
            font-size: 16px;
            width: 100%;
            text: root.label;
        }

        Rectangle {
            background: Colors.input-background;
            border-radius: 4px;
            border-color: Colors.input-border;
            border-width: 1px;

            VerticalLayout {
                padding: 4px;
                height: self.preferred-height;

                TextInput {
                    text <=> root.value;
                    vertical-alignment: center;
                    font-size: 16px;
                }
            }
        }
    }
}
