export global Colors {
    out property <color> panel-background: #17181ba4;
    out property <color> card-background: #202124;
    out property <color> input-background: #282a2d;
    out property <color> input-border: #5f6368;
    out property <color> button-background: #282a2d;
    out property <color> button-background-hovered: #36383a;
    out property <color> button-background-pressed: #464849;
    out property <color> card-background-selected: yellow;
    out property <color> text-color: white;
    out property <color> text-color-selected: black;
}
