import { Colors } from "../globals/colors.slint";
import { Textfield } from "../common/textfield.slint";
import { InterfaceState } from "../globals/state.slint";
import { ComponentData, KeyValuePair } from "../models/ComponentData.slint";

export component ComponentListItem {
    in property <string> component-json;
    in property <string> entity-id;
    in property <string> title;
    in property <[KeyValuePair]> fields;

    Rectangle {
        border-radius: 6px;
        background: Colors.card-background;

        VerticalLayout {
            padding: 12px;
            spacing: 8px;
            
            Text {
                text: title;
                font-size: 16px;
                font-weight: 700;
                width: 100%;
                horizontal-alignment: center;
                color: Colors.text-color;
            }
            
            // Component-specific fields editor
            for pair in fields: Textfield {
                label: pair.key;
                value: pair.value;
                value-changed(field_key, new_value) => {
                    // Request component JSON update from Rust
                    InterfaceState.update-component-field(root.entity-id, root.title, field_key, new_value);
                }
            }
        }
    }
}
