import { Colors } from "../globals/colors.slint";
import { Textfield } from "../common/textfield.slint";
import { ComponentUI } from "../models/ComponentUI.slint";
import { AttributeUI } from "../models/AttributeUI.slint";

export component ComponentListItem {
    in property <ComponentUI> component;
    in property <string> entity-id;
    
    Rectangle {
        border-radius: 6px;
        background: Colors.card-background;

        VerticalLayout {
            padding-top: 12px;
            padding-bottom: 12px;
            Text {
                text: component.name;
                font-size: 16px;
                width: 100%;
                horizontal-alignment: center;
            }

            for attributes in component.attributes: Textfield {
                label: attributes.name;
                value: attributes.value;
                entity-id: root.entity-id;
                component-name: component.name;
            }
        }
    }
}
