import { Colors } from "../globals/colors.slint";
import { InterfaceState } from "../globals/state.slint";

export component EntityListItem {
    in property <string> title;
    in property <string> entity-id;

    TouchArea {
        width: 100%;
        mouse-cursor: pointer;
        Rectangle {
            border-radius: 6px;
            background: InterfaceState.selected-index == root.entity-id ? Colors.card-background-selected : Colors.card-background;
            border-width: 1px;
            border-color: parent.has-hover ? Colors.card-background-selected : Colors.card-background;
            VerticalLayout {
                padding-top: 8px;
                padding-bottom: 8px;
                padding-left: 12px;
                padding-right: 12px;

                Text {
                    width: 100%;
                    text: root.title;
                    color: InterfaceState.selected-index == root.entity-id ? Colors.text-color-selected : Colors.text-color;
                    font-size: 16px;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                }
            }
        }

        clicked => {
            InterfaceState.selected-index = root.entity-id;
            InterfaceState.selected-title = root.title;
        }
    }
}
