import { Colors } from "../globals/colors.slint";
import { InterfaceState } from "../globals/state.slint";
import { Panel } from "../common/panel.slint";
import { EntityListItem } from "../components/entity-list-item.slint";
import { ComponentListItem } from "../components/component-list-item.slint";
import { Button } from "../common/button.slint";
import { TopBar } from "../components/top-bar.slint";

export component LevelEditorUI inherits Window {
    min-width: 800px;
    min-height: 600px;
    background: transparent;

    VerticalLayout {
        TopBar { }

        HorizontalLayout {
            width: 100%;
            spacing: 10px;
            padding: 15px;
            alignment: space-between;

            Panel {
                width: 300px;

                for entity in InterfaceState.entities: EntityListItem {
                    title: entity.title;
                    entity-id: entity.entity_id;
                }
            }

            if InterfaceState.selected-index != "":Panel {
                width: 300px;

                Button {
                    text: "Close";
                    on-click => {
                        InterfaceState.selected-index = "";
                        InterfaceState.entity-deselected();
                    }
                }

                Text {
                    width: 100%;
                    horizontal-alignment: center;
                    text: InterfaceState.selected-title;
                    font-size: 24px;
                    color: Colors.card-background-selected;
                }

                ComponentListItem {
                    component-json: InterfaceState.components-json;
                    entity-id: InterfaceState.selected-index;
                }
            }
        }
    }
}
